name: kscb_2024
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2024.7.4=h56e8100_0
  - libexpat=2.6.2=h63175ca_0
  - libffi=3.4.2=h8ffe710_5
  - libsqlite=3.46.0=h2466b09_0
  - libzlib=1.3.1=h2466b09_1
  - openssl=3.3.1=h2466b09_2
  - pip=24.0=pyhd8ed1ab_0
  - python=3.11.9=h631f459_0_cpython
  - setuptools=71.0.4=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=h8a93ad2_20
  - vc14_runtime=14.40.33810=ha82c5b3_20
  - vs2015_runtime=14.40.33810=h3bf8584_20
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h8d14728_0
  - pip:
    - anyio==4.4.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.1
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.15.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - certifi==2024.7.4
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - colorama==0.4.6
    - comm==0.2.2
    - debugpy==1.8.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==2.0.1
    - fastjsonschema==2.20.0
    - fqdn==1.5.1
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - idna==3.7
    - imutils==0.5.4
    - ipykernel==6.29.5
    - ipython==8.26.0
    - isoduration==20.11.0
    - jedi==0.19.1
    - jinja2==3.1.4
    - json5==0.9.25
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - jupyter-events==0.10.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.2.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - markupsafe==2.1.5
    - matplotlib-inline==0.1.7
    - mistune==3.0.2
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - notebook==7.2.1
    - notebook-shim==0.2.4
    - numpy==2.0.1
    - opencv-python==4.10.0.84
    - overrides==7.7.0
    - packaging==24.1
    - pandocfilters==1.5.1
    - parso==0.8.4
    - platformdirs==4.2.2
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.47
    - psutil==6.0.0
    - pure-eval==0.2.3
    - pycparser==2.22
    - pygame==2.6.0
    - pygments==2.18.0
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pywin32==306
    - pywinpty==2.0.13
    - pyyaml==6.0.1
    - pyzmq==26.0.3
    - referencing==0.35.1
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.19.0
    - send2trash==1.8.3
    - six==1.16.0
    - sniffio==1.3.1
    - soupsieve==2.5
    - stack-data==0.6.3
    - terminado==0.18.1
    - tinycss2==1.3.0
    - tornado==6.4.1
    - traitlets==5.14.3
    - types-python-dateutil==2.9.0.20240316
    - typing-extensions==4.12.2
    - uri-template==1.3.0
    - urllib3==2.2.2
    - wcwidth==0.2.13
    - webcolors==24.6.0
    - webencodings==0.5.1
    - websocket-client==1.8.0
prefix: C:\Users\neuroLaptop\anaconda3\envs\kscb_2024
